### ISSUE TITLE
Update function list

### ISSUE THREAD

**Issue by Mouvedia** [niksy/css-functions-list#7]
add
  - `color-stop`, `from`, `to`
  - `anchor`, `anchor-size`
  - `palette-mix`
 
remove
 - `image-rect`
 - `-o-image-rect`
 - `-ms-image-rect`
 - `-webkit-image-rect`

see
- stylelint/stylelint#7607
- https://github.com/stylelint/stylelint/issues/7226#issuecomment-1763395283
- https://developer.mozilla.org/en-US/docs/Web/CSS/font-palette/palette-mix
- https://caniuse.com/mdn-css_properties_background-image_image-rect
- https://bugs.webkit.org/show_bug.cgi?id=32177

**Comment by niksy** [comment]
Thanks for reporting issue!

These are references we use to gather functions list:

* https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions
* https://developer.mozilla.org/en-US/docs/Web/CSS/Reference
* https://github.com/mdn/browser-compat-data/tree/main/css/types

Since these values are not available on those links, we can’t automatically add them. Do you have reference for all the values you mentioned? `anchor-size` isn’t even available on Can I Use.

**Comment by Mouvedia** [comment]
> Since these values are not available on those links, we can’t automatically add them.

`palette-mix` is under `.sidebar-body` but you are right that not everything is listed.

> Do you have reference for all the values you mentioned?

The _see_ list should justify all the addition/deletion.

> `anchor-size` isn’t even available on Can I Use.

see _references_ in stylelint/stylelint#7566

**Comment by niksy** [comment]
> The see list should justify all the addition/deletion.

* `palette-mix` is still experimental and not listed in their official CSS functions list. Maybe see if it can be first added to MDN content so we can fetch it like all the other functions? Prior work on similar cases: https://github.com/niksy/css-functions-list/pull/4#issuecomment-1100305306
* `anchor` and `anchor-size` are still in draft stage and I don’t see them referenced anywhere

> check references in stylelint/stylelint#7566

These are all exceptions to functions listed here for obvious reasons (e.g. not available in listed sources).

Maybe we can [create exceptions like we do for `-webkit-gradient`](https://github.com/niksy/css-functions-list/blob/master/generate-list.js#L160-L165). Can you send PR with necessary changes?

**Comment by Mouvedia** [comment]
> Maybe we can [create exceptions like we do for `-webkit-gradient`](https://github.com/niksy/css-functions-list/blob/master/generate-list.js?rgh-link-date=2024-04-19T10%3A37%3A26Z#L160-L165). Can you send PR with necessary changes?

When I won't be busy I will. Last time I did directly but I wanted to be more careful this time around.
